<?php

return [
    'items' => [
        [
            'type' => 'hero',
            'label' => 'Hero',
            'status' => 'enabled',
            'category' => 'content',
            'description' => 'Large intro section with headline and CTA.',
        ],
        [
            'type' => 'text',
            'label' => 'Text',
            'status' => 'enabled',
            'category' => 'content',
            'description' => 'Rich text section for narrative content.',
        ],
        [
            'type' => 'image',
            'label' => 'Image',
            'status' => 'enabled',
            'category' => 'media',
            'description' => 'Single image block with optional caption.',
        ],
        [
            'type' => 'video',
            'label' => 'Video',
            'status' => 'enabled',
            'category' => 'media',
            'description' => 'Single featured video for explainers, campaigns, or ambience reels.',
        ],
        [
            'type' => 'video_grid',
            'label' => 'Video Grid',
            'status' => 'enabled',
            'category' => 'media',
            'description' => 'Grid of multiple video cards for tutorials, reels, or featured clips.',
        ],
        [
            'type' => 'slideshow',
            'label' => 'Slideshow',
            'status' => 'enabled',
            'category' => 'media',
            'description' => 'Image slideshow with captions and optional CTA per slide.',
        ],
        [
            'type' => 'photogrid',
            'label' => 'Photo Grid',
            'status' => 'enabled',
            'category' => 'media',
            'description' => 'Richer multi-image grid with title and caption per photo.',
        ],
        [
            'type' => 'feature_grid',
            'label' => 'Feature Grid',
            'status' => 'enabled',
            'category' => 'content',
            'description' => 'Grid of selling points or package highlights.',
        ],
        [
            'type' => 'gallery',
            'label' => 'Gallery',
            'status' => 'enabled',
            'category' => 'media',
            'description' => 'Image gallery for destination or room highlights.',
        ],
        [
            'type' => 'faq',
            'label' => 'FAQ',
            'status' => 'enabled',
            'category' => 'content',
            'description' => 'Frequently asked questions with answers.',
        ],
        [
            'type' => 'social_media',
            'label' => 'Social Media',
            'status' => 'enabled',
            'category' => 'content',
            'description' => 'Social media icon links for profile discovery and trust.',
        ],
        [
            'type' => 'timeline',
            'label' => 'Timeline',
            'status' => 'enabled',
            'category' => 'content',
            'description' => 'Milestones, journey steps, or process stages in timeline form.',
        ],
        [
            'type' => 'dynamic_collection',
            'label' => 'Dynamic Collection',
            'status' => 'enabled',
            'category' => 'system',
            'description' => 'Render published entries from a selected content type.',
        ],
        [
            'type' => 'form',
            'label' => 'Form',
            'status' => 'enabled',
            'category' => 'system',
            'description' => 'Link a page builder section to an existing Rawdee form.',
        ],
        [
            'type' => 'cta',
            'label' => 'CTA',
            'status' => 'enabled',
            'category' => 'content',
            'description' => 'Call-to-action card with button.',
        ],
        [
            'type' => 'spacer',
            'label' => 'Spacer',
            'status' => 'enabled',
            'category' => 'utility',
            'description' => 'Vertical spacing between sections.',
        ],
    ],
];
